package example06;

/*
public class ex6 {
    public static void main(String[] args) {
        try {
            System.out.println("0");
            throw new NullPointerException("ошибка");
        } catch (ArithmeticException e) {
            System.out.println("1" );
        }catch (Exception e) {
            System.out.println("2" );
        }catch (RuntimeException e) { // не будет перехватывается, так как исключение перехваченно в Exception
            System.out.println("3" );// в который входит RuntimeException
        }
        System.out.println("4");
    }

}
*/